# Generated by Django 2.1.2 on 2018-10-31 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('marketplace', models.TextField(blank=True, null=True)),
                ('customer_id', models.IntegerField(blank=True, null=True)),
                ('review_id', models.TextField(blank=True, null=True)),
                ('product_id', models.TextField(blank=True, null=True)),
                ('product_parent', models.IntegerField(blank=True, null=True)),
                ('product_title', models.TextField(blank=True, null=True)),
                ('product_category', models.TextField(blank=True, null=True)),
                ('star_rating', models.TextField(blank=True, null=True)),
                ('helpful_votes', models.FloatField(blank=True, null=True)),
                ('total_votes', models.FloatField(blank=True, null=True)),
                ('vine', models.TextField(blank=True, null=True)),
                ('verified_purchase', models.TextField(blank=True, null=True)),
                ('review_headline', models.TextField(blank=True, null=True)),
                ('review_body', models.TextField(blank=True, null=True)),
                ('review_date', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('index', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('marketplace', models.TextField(blank=True, null=True)),
                ('customer_id', models.IntegerField(blank=True, null=True)),
                ('review_id', models.TextField(blank=True, null=True)),
                ('product_id', models.TextField(blank=True, null=True)),
                ('product_parent', models.IntegerField(blank=True, null=True)),
                ('product_title', models.TextField(blank=True, null=True)),
                ('product_category', models.TextField(blank=True, null=True)),
                ('star_rating', models.TextField(blank=True, null=True)),
                ('helpful_votes', models.FloatField(blank=True, null=True)),
                ('total_votes', models.FloatField(blank=True, null=True)),
                ('vine', models.TextField(blank=True, null=True)),
                ('verified_purchase', models.TextField(blank=True, null=True)),
                ('review_headline', models.TextField(blank=True, null=True)),
                ('review_body', models.TextField(blank=True, null=True)),
                ('review_date', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movies',
                'managed': False,
            },
        ),
    ]
