# Generated by Django 2.1.2 on 2018-12-07 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_selection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Selection',
        ),
    ]
